# Generated by Django 3.0.8 on 2022-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(max_length=225)),
                ('product', models.CharField(max_length=225)),
                ('teeth1', models.IntegerField()),
                ('teeth2', models.IntegerField()),
                ('teeth3', models.IntegerField()),
                ('teeth4', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
