# Generated by Django 3.0.8 on 2022-04-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220412_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
