# Generated by Django 3.0.8 on 2022-04-12 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220412_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_detials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=225)),
                ('teeth1', models.IntegerField()),
                ('teeth2', models.IntegerField()),
                ('teeth3', models.IntegerField()),
                ('teeth4', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
                ('patient_name', models.CharField(max_length=225)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
        migrations.AlterField(
            model_name='payments',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
        migrations.DeleteModel(
            name='bill',
        ),
    ]
